/* Generated By:JavaCC: Do not edit this line. TopScriptTreeConstants.java Version 5.0 */
package topScript;

public interface TopScriptTreeConstants
{
  public int JJTSTART = 0;
  public int JJTLETRAMINUSCULA = 1;
  public int JJTLETRAMAIUSCULA = 2;
  public int JJTNUMERO = 3;
  public int JJTINICIOPROG = 4;
  public int JJTFIMPROG = 5;
  public int JJTSE = 6;
  public int JJTSENAO = 7;
  public int JJTPARA = 8;
  public int JJTENQUANTO = 9;
  public int JJTPRINT = 10;
  public int JJTATRIBUI = 11;
  public int JJTMAISMAIS = 12;
  public int JJTMENOSMENOS = 13;
  public int JJTBOOLTRUE = 14;
  public int JJTBOOLFALSE = 15;
  public int JJTABRECHAVES = 16;
  public int JJTFECHACHAVES = 17;
  public int JJTSEPARADOR = 18;
  public int JJTABREPARENTESES = 19;
  public int JJTFECHAPARENTESES = 20;
  public int JJTABRECOLCHETES = 21;
  public int JJTFECHACOLCHETES = 22;
  public int JJTVIRGULA = 23;
  public int JJTPONTO = 24;
  public int JJTASPA = 25;
  public int JJTTIPONUMERO = 26;
  public int JJTTIPOTEXTO = 27;
  public int JJTTIPOBOOL = 28;
  public int JJTTIPOFUNCAO = 29;
  public int JJTOPSUM = 30;
  public int JJTOPSUB = 31;
  public int JJTOPMUL = 32;
  public int JJTOPDIV = 33;
  public int JJTOPMOD = 34;
  public int JJTOPAND = 35;
  public int JJTOPOR = 36;
  public int JJTOPGT = 37;
  public int JJTOPLT = 38;
  public int JJTOPEQ = 39;
  public int JJTOPDIF = 40;
  public int JJTRETORNO = 41;
  public int JJTTEXTO = 42;
  public int JJTSTRING = 43;
  public int JJTFUNCAO = 44;
  public int JJTCONSTANTE = 45;
  public int JJTIDTIPO = 46;
  public int JJTIDNOME = 47;
  public int JJTATRIBUICAO = 48;
  public int JJTDECLARAVARIAVEL = 49;
  public int JJTOPERADORLOGICO = 50;
  public int JJTEXPRESSAOLOGICA = 51;
  public int JJTCONDICIONAL = 52;
  public int JJTREPETICAOPARA = 53;
  public int JJTREPETICAOENQUANTO = 54;
  public int JJTEXECUTARFUNCAO = 55;
  public int JJTTOP = 56;
  public int JJTCREMENTOS = 57;
  public int JJTBLOCO = 58;


  public String[] jjtNodeName = {
    "Start",
    "letraMinuscula",
    "letraMaiuscula",
    "numero",
    "inicioprog",
    "fimprog",
    "se",
    "senao",
    "para",
    "enquanto",
    "print",
    "atribui",
    "maisMais",
    "menosMenos",
    "boolTrue",
    "boolFalse",
    "abreChaves",
    "fechaChaves",
    "separador",
    "abreParenteses",
    "fechaParenteses",
    "abreColchetes",
    "fechaColchetes",
    "virgula",
    "ponto",
    "aspa",
    "tipoNumero",
    "tipoTexto",
    "tipoBool",
    "tipoFuncao",
    "opSum",
    "opSub",
    "opMul",
    "opDiv",
    "opMod",
    "opAnd",
    "opOr",
    "opGt",
    "opLt",
    "opEq",
    "opDif",
    "retorno",
    "texto",
    "string",
    "funcao",
    "constante",
    "idTipo",
    "idNome",
    "atribuicao",
    "declaraVariavel",
    "operadorLogico",
    "expressaoLogica",
    "condicional",
    "repeticaoPara",
    "repeticaoEnquanto",
    "executarFuncao",
    "top",
    "crementos",
    "bloco",
  };
}
/* JavaCC - OriginalChecksum=fdea1a29e7603d518dc8206451f66b1c (do not edit this line) */
