/* Generated By:JJTree&JavaCC: Do not edit this line. TopScriptConstants.java */
package topScript;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TopScriptConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIOPROG = 7;
  /** RegularExpression Id. */
  int FIMPROG = 8;
  /** RegularExpression Id. */
  int SE = 9;
  /** RegularExpression Id. */
  int SENAO = 10;
  /** RegularExpression Id. */
  int PARA = 11;
  /** RegularExpression Id. */
  int ENQUANTO = 12;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int RETORNO = 14;
  /** RegularExpression Id. */
  int ATRIBUI = 15;
  /** RegularExpression Id. */
  int MAIS_MAIS = 16;
  /** RegularExpression Id. */
  int MENOS_MENOS = 17;
  /** RegularExpression Id. */
  int BOOL_TRUE = 18;
  /** RegularExpression Id. */
  int BOOL_FALSE = 19;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 20;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 21;
  /** RegularExpression Id. */
  int SEPARADOR = 22;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 23;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 24;
  /** RegularExpression Id. */
  int ABRE_COLCHETES = 25;
  /** RegularExpression Id. */
  int FECHA_COLCHETES = 26;
  /** RegularExpression Id. */
  int VIRGULA = 27;
  /** RegularExpression Id. */
  int PONTO = 28;
  /** RegularExpression Id. */
  int ASPA = 29;
  /** RegularExpression Id. */
  int TIPO_NUMERO = 30;
  /** RegularExpression Id. */
  int TIPO_TEXTO = 31;
  /** RegularExpression Id. */
  int TIPO_BOOL = 32;
  /** RegularExpression Id. */
  int TIPO_FUNCAO = 33;
  /** RegularExpression Id. */
  int OP_SUM = 34;
  /** RegularExpression Id. */
  int OP_SUB = 35;
  /** RegularExpression Id. */
  int OP_MUL = 36;
  /** RegularExpression Id. */
  int OP_DIV = 37;
  /** RegularExpression Id. */
  int OP_MOD = 38;
  /** RegularExpression Id. */
  int OP_AND = 39;
  /** RegularExpression Id. */
  int OP_OR = 40;
  /** RegularExpression Id. */
  int OP_GT = 41;
  /** RegularExpression Id. */
  int OP_LT = 42;
  /** RegularExpression Id. */
  int OP_EQ = 43;
  /** RegularExpression Id. */
  int OP_DIF = 44;
  /** RegularExpression Id. */
  int LETRA_MAIUSCULA = 45;
  /** RegularExpression Id. */
  int LETRA_MINUSCULA = 46;
  /** RegularExpression Id. */
  int DIGITO = 47;
  /** RegularExpression Id. */
  int NUMERO = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"\\ud83d\\udd1d\"",
    "\"\\ud83d\\udd1a\"",
    "\"\\ud83e\\udd14\"",
    "\"\\ud83d\\ude44\"",
    "\"\\ud83d\\udd01\"",
    "\"\\ud83d\\udd04\"",
    "\"\\ud83e\\udd2c\"",
    "\"\\u21aa\\ufe0f\"",
    "\"\\u270d\\ufe0f\"",
    "\"\\u23eb\"",
    "\"\\u23ec\"",
    "\"\\ud83d\\udc4d\"",
    "\"\\ud83d\\udc4e\"",
    "\"\\ud83d\\udc49\"",
    "\"\\ud83d\\udc48\"",
    "\"\\ud83d\\udc4c\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\"\\\'\"",
    "\"#\\ufe0f\\u20e3\"",
    "\"\\ud83d\\udd21\"",
    "\"\\ud83d\\udebb\"",
    "\"\\u25b6\\ufe0f\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"\\ud83c\\udd70\\ufe0f\"",
    "\"\\ud83c\\udd7e\\ufe0f\"",
    "\">\"",
    "\"<\"",
    "\"\\ud83e\\udd1d\"",
    "\"\\u2757\"",
    "<LETRA_MAIUSCULA>",
    "<LETRA_MINUSCULA>",
    "<DIGITO>",
    "<NUMERO>",
  };

}
